### ISSUE TITLE
Ouflow Threw A Error - HarmonyLib.HarmonyException: Patching exception in method null

### ISSUE THREAD

**Issue by TumnusB** [RileyGuy/Outflow#5]
https://pastebin.com/uu7Z9yeS

**Comment by BlueCyro** [comment]
Outflow is deprecated as per Resonite update `2024.9.30.1215`, I just haven't gotten around to archiving this repo yet. Hitches in voice and streamed data when people join a session has been fixed in the main game. Outflow is not longer required.
